services:
  markitdown:
    build: .
    container_name: markitdown-converter
    ports:
      - "5001:5000"
    environment:
      - SESSION_SECRET=your-secret-key-here
    volumes:
      - .:/app
    restart: unless-stopped