version: '3.8'

services:
  markitdown:
    build: .
    container_name: markitdown-converter
    ports:
      - "5000:5000"
    environment:
      - SESSION_SECRET=your-secret-key-here
    volumes:
      - ./app:/app
    restart: unless-stopped